# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0002_auto_20170127_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Birthday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.ForeignKey(default=1988, on_delete=django.db.models.deletion.CASCADE, to='belt.Birthday'),
            preserve_default=False,
        ),
    ]
