# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0003_auto_20170127_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='Birthday',
        ),
    ]
